### ISSUE TITLE
Using :/ rather than :// in Samples.HTTPGet leads to an untrapped error in HostPort

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/Conga-apl#1]
Missed the second "/" by mistake.

      Samples.HTTPGet'http:/www.dyalog.com'
INDEX ERROR
HostPort[4] port←1⊃2⊃⎕VFI z↓host ⋄ host←(z-1)↑host  ⍝ Use :port if found in host name
           ∧

Any chance of doing a little more to spot this (unintentional) error ?

**Comment by bpbecker** [comment]
I've added additional argument checking in the HTTP functions in Samples.
